services:
  bmkg-bot:
    build: .
    container_name: bmkg-bot
    restart: unless-stopped
    environment:
      # Setup Timezone agar log sesuai WIB
      - TZ=Asia/Jakarta
      # - WA_GATEWAY_URL=http://gowa:3006/whatsapp/send/message
      # - WA_TARGET_PHONE=6281xxx
      # - FILTER_PROVINCE=Jawa Barat, Bali
    env_file:
      - .env
    volumes:
      - ./history.json:/app/history.json
    networks:
      - infobmkg-bot-net

networks:
  infobmkg-bot-net:
    external: true
